on:
  workflow_dispatch:
  schedule:
    # GitHub Actions cron schedules are UTC-based 
    - cron: 45 1 6 * *  # '30 5,17 * * *' 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Proxy DAST Scan | altoro.testfire.net
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: active-scans

      - name: Run ZAP Full Scan | altoro.testfire.net
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://altoro.testfire.net'
          rules_file_name: 'rules/rules.altoro.testfire.net.tsv'
          allow_issue_writing: true
          issue_title: 'DAST Scan: altoro.testfire.net'
          cmd_options: -a -T 3 -n ./contexts/altoro.testfire.net.context

      - name: Publish Scan Results
        run: ./scripts/bash/publish_reports.sh 'altoro.testfire.net' $(pwd)
