on:
  workflow_dispatch:
  schedule:
    # GitHub Actions cron schedules are UTC-based 
    - cron: 15 4 15 * *  # '30 5,17 * * *' 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Proxy DAST Scan | public-firing-range.appspot.com
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: active-scans

      - name: Run ZAP Full Scan | public-firing-range.appspot.com
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://public-firing-range.appspot.com'
          rules_file_name: 'rules/rules.public-firing-range.appspot.com.tsv'
          allow_issue_writing: true
          issue_title: 'DAST Scan: public-firing-range.appspot.com'
          cmd_options: -a -T 3 -n ./contexts/public-firing-range.appspot.com.context

      - name: Publish Scan Results
        run: |
          chmod +x ./scripts/bash/publish_reports.sh
          ./scripts/bash/publish_reports.sh 'public-firing-range.appspot.com' $(pwd)
