name: Python + ZAP PoC

on: [push]

jobs:
  build:

    env:
      ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
          architecture: 'x64'

      - name: Install Python ZAP library
        run: pip install zaproxy

      - name: Install ZAP Proxy
        run: |
          sudo snap install zaproxy --classic
          # dpkg -L zaproxy

      - name: Run ZAP Proxy
        run: |
          zaproxy -daemon -config api.key="$ZAP_API_KEY" &

      - name: Run API scripts
        run: |
          sudo python dast/scripts/dast.py -k "$ZAP_API_KEY"
