name: Python + ZAP PoC

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ZAP Proxy
        run: |
          sudo apt-get install -y zaproxy
          dpkg -L zaproxy

      - name: Test ZAP
        run: zaproxy -version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
          architecture: 'x64'

      - name: Test Python stuff
        run: |
          python -c "import sys; print(f'Using Python {sys.version}')"
          # python dast/scripts/dast.py
