# on:
#   schedule: 
#     - cron: '15 0 1,15 * *' # https://crontab.guru/

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Proxy Baseline Scan - DAST PoC Target
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: zap-tests
      
      - name: Set Timestamp Environment Variable
        run: |
          echo "{timestamp}={$(date +%s)}" >> $GITHUB_STATE

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0 # zaproxy/action-baseline@v0.10.0 # TODO env variable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://altoro.testfire.net'
          rules_file_name: '.zap/rules.tsv'
          # TODO pass secrets in via variables for actual targets
          cmd_options: -a -T 3 -n .zap/contexts/authn_scan.context -r .zap/zap-${{ env.timestamp }}.html -J .zap/zap-${{ env.timestamp }}.json 
