# on:
#   schedule: 
#     - cron: '15 0 1,15 * *' # https://crontab.guru/

# on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Proxy Baseline Scan - DAST PoC Target
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0 # TODO env variable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://altoro.testfire.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -T 3' 
